/* The following code was generated by JFlex 1.4.3 on 17/05/11 14:29 */

package com.mn.plug.idea.sparql4idea.lang.lexer;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;

import static com.mn.plug.idea.sparql4idea.lang.lexer.SparqlTokenTypes.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 17/05/11 14:29 from the specification file
 * <tt>/home/matt/projects/opensource/github/sparql4idea/source/sparql4idea/src/com/mn/plug/idea/sparql4idea/lang/lexer/_SparqlLexer.flex</tt>
 */
class _SparqlLexer implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\1\0\2\0\1\0\5\0\1\3\1\3\2\0\1\3\22\0\1\3"+
    "\1\0\1\0\1\0\1\0\2\0\1\0\1\0\1\0\1\0\1\0"+
    "\1\0\1\0\1\0\1\0\1\0\1\0\1\0\7\0\1\0\1\0"+
    "\1\0\1\0\1\0\1\0\1\0\1\7\1\6\1\15\1\21\1\2"+
    "\1\5\1\30\1\27\1\13\2\0\1\14\1\23\1\4\1\24\1\11"+
    "\1\0\1\12\1\10\1\16\1\20\1\0\1\26\1\1\1\22\1\0"+
    "\1\0\1\0\1\0\1\0\1\0\1\0\1\31\1\6\1\15\1\25"+
    "\1\2\1\5\1\30\1\27\1\13\2\0\1\14\1\23\1\4\1\17"+
    "\1\11\1\0\1\12\1\32\1\16\1\20\1\0\1\26\1\1\1\22"+
    "\1\0\3\0\162\0\11\0\1\0\3\0\1\0\uff02\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\16\1\1\3\5\0\1\4\31\0"+
    "\1\5\23\0\1\6\1\0\1\7\11\0\1\10\13\0"+
    "\1\11\1\0\1\12\4\0\1\13\1\14\1\0\1\15"+
    "\1\0\1\16\3\0\1\17\1\20\3\0\1\21\1\22"+
    "\1\23\1\24\1\0\1\25\4\0\1\26\5\0\1\27"+
    "\7\0\1\30\3\0\1\31\1\32\1\33\1\34\1\35"+
    "\1\0\1\36\1\0\1\37";

  private static int [] zzUnpackAction() {
    int [] result = new int[151];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\33\0\33\0\66\0\121\0\154\0\207\0\242"+
    "\0\275\0\330\0\363\0\u010e\0\u0129\0\u0144\0\u015f\0\u017a"+
    "\0\u0195\0\33\0\u01b0\0\u01cb\0\u01e6\0\u0201\0\u021c\0\33"+
    "\0\u0237\0\u0252\0\u026d\0\u0288\0\u02a3\0\u02be\0\u02d9\0\u02f4"+
    "\0\u030f\0\u032a\0\u0345\0\u0360\0\u037b\0\u0396\0\u03b1\0\u03cc"+
    "\0\u03e7\0\u0402\0\u041d\0\u0438\0\u0453\0\u046e\0\u0489\0\u04a4"+
    "\0\u04bf\0\33\0\u04da\0\u04f5\0\u0510\0\u052b\0\u0546\0\u0561"+
    "\0\u057c\0\u0597\0\u05b2\0\u05cd\0\u05e8\0\u0603\0\u061e\0\u0639"+
    "\0\u0654\0\u066f\0\u068a\0\u06a5\0\u06c0\0\33\0\u06db\0\33"+
    "\0\u06f6\0\u0711\0\u072c\0\u0747\0\u0762\0\u077d\0\u0798\0\u07b3"+
    "\0\u07ce\0\u07e9\0\u0804\0\u081f\0\u083a\0\u0855\0\u0870\0\u088b"+
    "\0\u08a6\0\u08c1\0\u08dc\0\u08f7\0\u0912\0\33\0\u092d\0\33"+
    "\0\u0948\0\u0963\0\u097e\0\u0999\0\33\0\33\0\u09b4\0\33"+
    "\0\u09cf\0\33\0\u09ea\0\u0a05\0\u0a20\0\33\0\33\0\u0a3b"+
    "\0\u0a56\0\u0a71\0\33\0\33\0\33\0\33\0\u0a8c\0\33"+
    "\0\u0aa7\0\u0ac2\0\u0add\0\u0af8\0\33\0\u0b13\0\u0b2e\0\u0b49"+
    "\0\u0b64\0\u0b7f\0\33\0\u0b9a\0\u0bb5\0\u0bd0\0\u0beb\0\u0c06"+
    "\0\u0c21\0\u0c3c\0\33\0\u0c57\0\u0c72\0\u0c8d\0\33\0\33"+
    "\0\33\0\33\0\33\0\u0ca8\0\33\0\u0cc3\0\33";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[151];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\3\2\1\3\1\4\1\5\1\6\1\2\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\2\1\15\1\16\1\17"+
    "\2\2\1\15\1\17\1\20\1\2\1\21\1\22\1\7"+
    "\42\0\1\23\21\0\1\23\13\0\1\24\1\25\26\0"+
    "\1\26\7\0\1\27\2\0\1\30\1\0\1\27\4\0"+
    "\1\26\3\0\1\31\4\0\1\32\6\0\1\33\12\0"+
    "\1\32\13\0\1\34\22\0\1\35\40\0\1\36\21\0"+
    "\1\36\7\0\1\37\3\0\1\40\15\0\1\37\20\0"+
    "\1\41\4\0\1\41\13\0\1\42\3\0\1\43\1\44"+
    "\24\0\1\45\30\0\1\46\4\0\1\47\3\0\1\50"+
    "\15\0\1\47\30\0\1\51\15\0\1\52\43\0\1\53"+
    "\33\0\2\54\21\0\1\55\26\0\1\56\21\0\1\56"+
    "\20\0\1\57\26\0\1\60\41\0\1\61\21\0\1\62"+
    "\22\0\1\63\51\0\1\64\3\0\1\64\2\0\1\65"+
    "\15\0\1\66\1\67\3\0\1\70\16\0\1\71\51\0"+
    "\1\72\13\0\1\73\33\0\1\74\43\0\1\75\35\0"+
    "\1\76\3\0\1\76\20\0\1\77\27\0\1\100\21\0"+
    "\1\100\16\0\1\101\24\0\1\102\21\0\1\102\2\0"+
    "\1\103\37\0\1\104\21\0\1\104\3\0\1\105\53\0"+
    "\1\106\25\0\1\107\16\0\1\110\34\0\1\111\30\0"+
    "\1\112\32\0\1\113\35\0\1\114\45\0\1\115\14\0"+
    "\1\116\42\0\1\117\33\0\1\120\31\0\1\121\50\0"+
    "\1\122\15\0\1\123\27\0\1\124\21\0\1\124\10\0"+
    "\1\125\21\0\1\125\13\0\1\126\21\0\1\127\47\0"+
    "\1\130\4\0\1\130\23\0\1\131\24\0\1\132\21\0"+
    "\1\132\17\0\1\133\26\0\1\134\31\0\1\135\42\0"+
    "\1\136\3\0\1\136\7\0\1\137\51\0\1\140\3\0"+
    "\1\140\22\0\1\141\33\0\1\142\27\0\1\143\34\0"+
    "\1\144\16\0\1\145\44\0\1\146\35\0\1\147\27\0"+
    "\1\150\42\0\1\151\25\0\1\152\32\0\1\153\16\0"+
    "\1\154\47\0\1\155\4\0\1\155\20\0\1\156\24\0"+
    "\1\157\40\0\1\160\36\0\1\161\27\0\1\162\21\0"+
    "\1\163\57\0\1\164\15\0\1\165\36\0\1\166\16\0"+
    "\1\167\31\0\1\170\33\0\1\171\32\0\1\172\37\0"+
    "\1\173\22\0\1\173\12\0\1\174\36\0\1\175\20\0"+
    "\1\176\41\0\1\177\41\0\1\200\14\0\1\201\40\0"+
    "\1\202\41\0\1\203\3\0\1\203\17\0\1\204\36\0"+
    "\1\205\34\0\1\206\21\0\1\207\21\0\1\207\7\0"+
    "\1\210\35\0\1\211\36\0\1\212\40\0\1\213\16\0"+
    "\1\214\21\0\1\214\16\0\1\215\32\0\1\216\31\0"+
    "\1\217\20\0\1\220\32\0\1\221\46\0\1\222\30\0"+
    "\1\223\45\0\1\224\21\0\1\225\16\0\1\226\40\0"+
    "\1\227\21\0\1\227";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3294];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\16\1\1\11\5\0\1\11\31\0\1\11"+
    "\23\0\1\11\1\0\1\11\11\0\1\1\13\0\1\11"+
    "\1\0\1\11\4\0\2\11\1\0\1\11\1\0\1\11"+
    "\3\0\2\11\3\0\4\11\1\0\1\11\4\0\1\11"+
    "\5\0\1\11\7\0\1\11\3\0\5\11\1\0\1\11"+
    "\1\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[151];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;


  _SparqlLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  _SparqlLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 196) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL.charAt(zzCurrentPosL++);
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL.charAt(zzCurrentPosL++);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 31: 
          { return KW_LANGMATCHES;
          }
        case 32: break;
        case 7: 
          { return KW_BASE;
          }
        case 33: break;
        case 1: 
          { return BAD_CHARACTER;
          }
        case 34: break;
        case 18: 
          { return KW_GRAPH;
          }
        case 35: break;
        case 16: 
          { return KW_UNION;
          }
        case 36: break;
        case 26: 
          { return KW_DESCRIBE;
          }
        case 37: break;
        case 10: 
          { return KW_BOUND;
          }
        case 38: break;
        case 8: 
          { return KW_LANG;
          }
        case 39: break;
        case 14: 
          { return KW_LIMIT;
          }
        case 40: break;
        case 3: 
          { return KW_A;
          }
        case 41: break;
        case 29: 
          { return KW_IS_LITERAL;
          }
        case 42: break;
        case 25: 
          { return KW_OPTIONAL;
          }
        case 43: break;
        case 21: 
          { return KW_PREFIX;
          }
        case 44: break;
        case 22: 
          { return KW_OFFSET;
          }
        case 45: break;
        case 2: 
          { return WHITE_SPACE;
          }
        case 46: break;
        case 20: 
          { return KW_SELECT;
          }
        case 47: break;
        case 19: 
          { return KW_FILTER;
          }
        case 48: break;
        case 6: 
          { return KW_FROM;
          }
        case 49: break;
        case 13: 
          { return KW_IS_URI;
          }
        case 50: break;
        case 28: 
          { return KW_DISTINCT;
          }
        case 51: break;
        case 24: 
          { return KW_SAME_TERM;
          }
        case 52: break;
        case 17: 
          { return KW_WHERE;
          }
        case 53: break;
        case 5: 
          { return KW_STR;
          }
        case 54: break;
        case 27: 
          { return KW_DATATYPE;
          }
        case 55: break;
        case 23: 
          { return KW_REDUCED;
          }
        case 56: break;
        case 4: 
          { return KW_BY;
          }
        case 57: break;
        case 11: 
          { return KW_REGEX;
          }
        case 58: break;
        case 30: 
          { return KW_CONSTRUCT;
          }
        case 59: break;
        case 12: 
          { return KW_IS_IRI;
          }
        case 60: break;
        case 9: 
          { return KW_NAMED;
          }
        case 61: break;
        case 15: 
          { return KW_ORDER;
          }
        case 62: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
